/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"

int main(void)
{
	Clock_Init();
	GPIO_Init();
	while(1)
	{
		GPIOC->ODR |= (1<<13);
		myDelay(150);
		GPIOC->ODR &= ~(1<<13);
		myDelay(150);
	}
	return 0;
}
